name: timely
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core & State Management
  http: ^1.2.1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  package_info_plus: ^8.0.0
  logger: ^2.3.0
  url_launcher: ^6.2.2

  # UI & UX
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  google_nav_bar: ^5.0.6
  flutter_animate: ^4.5.0
  sticky_headers: ^0.3.0+2
  shimmer: ^3.0.0

  # Localization
  easy_localization: ^3.0.7

  # Utilities & Hardware
  geolocator: ^12.0.0
  image_picker: ^1.1.2
  image_cropper: ^7.0.5
  google_maps_flutter: ^2.7.0
  geocoding: ^3.0.0
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4

  # Document & Printing
  printing: ^5.12.0
  pdf: ^3.11.0

  # Charts
  syncfusion_flutter_charts: ^31.1.22

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logoapp.jpeg"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logo2.png"

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/maps/
